import SearchIndustries from "@/components/SearchIndustries/SearchIndustries";
import Head from "next/head";

const RooSearchIndustries = () => {
  return (
    <>
      <Head>
        <title>Roo Search - Industries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchIndustries />
    </>
  );
};

export default RooSearchIndustries;
