import RooSearch from "@/components/RooSearch/RooSearch";
import Head from "next/head";

const RooSearchPage = () => {
  return (
    <>
      <Head>
        <title>Roo Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RooSearch />
    </>
  );
};

export default RooSearchPage;
