import CapitalAbout from "@/components/CapitalAbout/CapitalAbout";
import Head from "next/head";

const About = () => {
  return (
    <>
      <Head>
        <title>Roo Capital - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CapitalAbout />
    </>
  );
};

export default About;
