import Contact from "@/components/Contact/Contact";
import Head from "next/head";

const RooSearchContact = () => {
  return (
    <>
      <Head>
        <title>Roo Search - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Contact condition={true} />
    </>
  );
};

export default RooSearchContact;
