import SearchAbout from "@/components/SearchAbout/SearchAbout";
import Head from "next/head";

const RooSearchAbout = () => {
  return (
    <>
      <Head>
        <title>Roo Search - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchAbout />
    </>
  );
};

export default RooSearchAbout;
