import SearchBio from "@/components/SearchBio/SearchBio";
import Head from "next/head";

const RooSearchBio = () => {
  return (
    <>
      <Head>
        <title>Roo Search - Bio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBio />
    </>
  );
};

export default RooSearchBio;
