import CapitalContact from "@/components/CapitalContact/CapitalContact";
import Head from "next/head";

const RooCapitalConact = () => {
  return (
    <>
      <Head>
        <title>Roo Capital - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CapitalContact condition={false} />
    </>
  );
};

export default RooCapitalConact;
