import Spotlight from "@/components/SearchSpotlight/Spotlight";
import Head from "next/head";

const RooSearchSpotlightPage = () => {
  return (
    <>
      <Head>
        <title>Roo Search - Spotlight</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Spotlight />
    </>
  );
};

export default RooSearchSpotlightPage;
