import Spotlight from "@/components/Spotlight/Spotlight";
import Head from "next/head";

const SpotlightPage = () => {
  return (
    <>
      <Head>
        <title>Roo Search - Spotlight</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Spotlight bgChange={false} />
    </>
  );
};

export default SpotlightPage;
