import Head from "next/head";
import Carousel from "@/components/Carousel/Carousel";

const RooSearchIndustries = () => {
  return (
    <>
      <Head>
        <title>Roo Search - Industries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel cardType="industry" />
    </>
  );
};

export default RooSearchIndustries;
